### PR TITLE
fix: custom flags with union type

### LINKED ISSUE #812: Custom flags with multiple: false
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Bug, I think.

What is the current behavior?
-----------------------------
Consider the following custom Flag:

```ts
export const versionSchemeFlag = Flags.custom<VersionScheme | undefined>({
	description: "Version scheme to use.",
	options: ["semver", "internal", "virtualPatch"],
	parse: async (input) => {
    	if (isVersionScheme(input)) {
			return input;
		}
	},
});
```

This declaration does not compile with oclif 4.0.0. The compiler complains that `multiple` is missing from the declaration, and `multiple: false` is not permitted. I have to set `multiple: true`. In other words, this DOES compile:

```ts
export const versionSchemeFlag = Flags.custom<VersionScheme | undefined>({
	description: "Version scheme to use.",
	options: ["semver", "internal", "virtualPatch"],
	parse: async (input) => {
    	if (isVersionScheme(input)) {
			return input;
		}
	},
	multiple: true,
});
```

What is the expected behavior?
------------------------------

In prior versions it was possible to declare a custom flag with multiple=false. I would expect to be able to do this in the most recent version.

oclif version
------------

oclif/4.0.0 linux-x64 node-v18.18.0

### PR DESCRIPTION
**Pull request by mdonnalley**
Fixes issue with custom flags with union type unnecessarily enforcing `multiple: true`

Fixes #812 

@W-14261473@

### CODE REVIEW

File: src/flags.ts [hunk 1]
```diff
@@ -145,39 +145,39 @@ export const help = (opts: Partial<BooleanFlag<boolean>> = {}): BooleanFlag<void
     },
   })
 
-type ElementType<T extends ReadonlyArray<unknown>> = T[number]
+type ReadonlyElementOf<T extends ReadonlyArray<unknown>> = T[number]
```
Comment (mdonnalley) [inline src/flags.ts:148]: This isn't part of the fix - I just thought it would be a clearer name for the type

**Review by shetzel — DISMISSED** [review]
