### PR TITLE
fix: support jsonc tsconfig

### LINKED ISSUE #849: loadTSConfig assume valid JSON
**Describe the bug**

The `loadTSConfig` function assumes `tsconfig.json` is JSON, however, `tsconfig.json` officially is a JSONC file, which allows for comments.

From: https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html#tsconfig

> The TSConfig is a jsonc file ...

https://github.com/oclif/core/blob/7aec22efe81948780e78486080f494c9e108f74c/src/config/ts-node.ts#L18-L45

Fails with:

> Warning: Could not parse tsconfig.json for .... Falling back to compiled source.

**To Reproduce**

- Add a comment to `tsconfig.json`
- Run a command

**Expected behavior**

Allow comments.

**Screenshots**

N/A

### PR DESCRIPTION
**Pull request by mdonnalley**
Always use `tsconfck` again for parse tsconfig.json

Fixes #849

### CODE REVIEW

**Review by shetzel — DISMISSED** [review]

**Comment by cristiand391** [comment]
**QA notes**:

setup: 
clone https://github.com/salesforcecli/plugin-deploy-retrieve/
yarn install then link this branch of core

✅ `bin/dev`: ts-node works, made change in `start.ts` then ran without compiling
⚠️ tsconfig with and without comments,  I get this warning (multiple times, but I think that's because of devPlugins).
```
➜  plugin-deploy-retrieve git:(main) ✗ DEBUG=*config:ts-node* ./bin/dev project deploy start
  config:ts-node registering ts-node at /Users/cdominguez/code/gh/sf/plugin-deploy-retrieve +0ms
  config:ts-node ts-node path: /Users/cdominguez/code/gh/sf/plugin-deploy-retrieve/node_modules/ts-node/dist/index.js +1ms
  config:ts-node tsconfig: {
  config:ts-node   extends: '@salesforce/dev-config/tsconfig-strict',
  config:ts-node   compilerOptions: {
  config:ts-node     outDir: 'lib',
  config:ts-node     rootDir: 'src',
  config:ts-node     skipLibCheck: true,
  config:ts-node     baseUrl: '/Users/cdominguez/code/gh/sf/plugin-deploy-retrieve',
  config:ts-node     paths: {
  config:ts-node       '@salesforce/core': [Array],
  config:ts-node       '@salesforce/source-deploy-retrieve': [Array]
  config:ts-node     },
  config:ts-node     strict: true,
  config:ts-node     module: 'commonjs',
  config:ts-node     target: 'es2021',
  config:ts-node     lib: [ 'es2021' ],
  config:ts-node     sourceMap: true,
  config:ts-node     declaration: true,
  config:ts-node     moduleResolution: 'node',
  config:ts-node     alwaysStrict: true,
  config:ts-node     noUnusedLocals: true
  config:ts-node   },
  config:ts-node   include: [ './src/**/*.ts' ],
  config:ts-node   'ts-node': {}
  config:ts-node } +3ms
  config:ts-node ts-node options: {
  config:ts-node   compilerOptions: {
  config:ts-node     outDir: 'lib',
  config:ts-node     skipLibCheck: true,
  config:ts-node     paths: {
  config:ts-node       '@salesforce/core': [Array],
  config:ts-node       '@salesforce/source-deploy-retrieve': [Array]
  config:ts-node     },
  config:ts-node     strict: true,
  config:ts-node     module: 'commonjs',
  config:ts-node     target: 'es2021',
  config:ts-node     lib: [ 'es2021' ],
  config:ts-node     sourceMap: true,
  config:ts-node     declaration: true,
  config:ts-node     moduleResolution: 'node',
  config:ts-node     alwaysStrict: true,
  config:ts-node     noUnusedLocals: true,
  config:ts-node     rootDirs: [ '/Users/cdominguez/code/gh/sf/plugin-deploy-retrieve/src' ],
  config:ts-node     typeRoots: [
  config:ts-node       '/Users/cdominguez/code/gh/sf/plugin-deploy-retrieve/node_modules/@types'
  config:ts-node     ]
  config:ts-node   },
  config:ts-node   cwd: '/Users/cdominguez/code/gh/sf/plugin-deploy-retrieve',
  config:ts-node   esm: true,
  config:ts-node   experimentalSpecifierResolution: 'explicit',
  config:ts-node   scope: true,
  config:ts-node   scopeDir: '/Users/cdominguez/code/gh/sf/plugin-deploy-retrieve',
  config:ts-node   skipProject: true,
  config:ts-node   transpileOnly: true
  config:ts-node } +2ms
  config:ts-node determining path for /Users/cdominguez/code/gh/sf/plugin-deploy-retrieve/lib/commands +1ms
  config:ts-node lib dir: /Users/cdominguez/code/gh/sf/plugin-deploy-retrieve/lib +0ms
  config:ts-node src dir: /Users/cdominguez/code/gh/sf/plugin-deploy-retrieve/src +0ms
  config:ts-node src commands dir: /Users/cdominguez/code/gh/sf/plugin-deploy-retrieve/src/commands +0ms
  config:ts-node Found source file for /Users/cdominguez/code/gh/sf/plugin-deploy-retrieve/lib/commands at /Users/cdominguez/code/gh/sf/plugin-deploy-retrieve/src/commands +0ms
  config:ts-node determining path for /Users/cdominguez/code/gh/sf/plugin-deploy-retrieve/lib/hooks/deploy +12ms
  config:ts-node lib dir: /Users/cdominguez/code/gh/sf/plugin-deploy-retrieve/lib +0ms
  config:ts-node src dir: /Users/cdominguez/code/gh/sf/plugin-deploy-retrieve/src +0ms
  config:ts-node src commands dir: /Users/cdominguez/code/gh/sf/plugin-deploy-retrieve/src/hooks/deploy +0ms
  config:ts-node Found source file for /Users/cdominguez/code/gh/sf/plugin-deploy-retrieve/lib/hooks/deploy at /Users/cdominguez/code/gh/sf/plugin-deploy-retrieve/src/hooks/deploy +0ms
  config:ts-node Could not parse tsconfig.json. Skipping ts-node registration for /Users/cdominguez/code/gh/sf/plugin-deploy-retrieve/node_modules/@oclif/plugin-help. +2s
Warning: Could not parse tsconfig.json for /Users/cdominguez/code/gh/sf/plugin-deploy-retrieve/node_modules/@oclif/plugin-help. Falling back to compiled source.
    at warn (/Users/cdominguez/code/gh/oclif/core/lib/errors/index.js:75:15)
    at memoizedWarn (/Users/cdominguez/code/gh/oclif/core/lib/errors/index.js:93:9)
    at loadTSConfig (/Users/cdominguez/code/gh/oclif/core/lib/config/ts-node.js:58:35)
    at async registerTSNode (/Users/cdominguez/code/gh/oclif/core/lib/config/ts-node.js:62:22)
    at async determinePath (/Users/cdominguez/code/gh/oclif/core/lib/config/ts-node.js:156:22)
    at async tsPath (/Users/cdominguez/code/gh/oclif/core/lib/config/ts-node.js:223:16)
    at async Plugin.load (/Users/cdominguez/code/gh/oclif/core/lib/config/plugin.js:156:28)
    at async /Users/cdominguez/code/gh/oclif/core/lib/config/plugin-loader.js:122:17
    at async Promise.all (index 1)
    at async PluginLoader.loadPlugins (/Users/cdominguez/code/gh/oclif/core/lib/config/plugin-loader.js:102:9)
    at async PluginLoader.loadDevPlugins (/Users/cdominguez/code/gh/oclif/core/lib/config/plugin-loader.js:90:21)
    at async PluginLoader.loadChildren (/Users/cdominguez/code/gh/oclif/core/lib/config/plugin-loader.js:49:13)
    at async Config.loadPluginsAndCommands (/Users/cdominguez/code/gh/oclif/core/lib/config/config.js:334:37)
    at async Config.load (/Users/cdominguez/code/gh/oclif/core/lib/config/config.js:322:9)
    at async Function.load (/Users/cdominguez/code/gh/oclif/core/lib/config/config.js:152:9)
    at async Object.run (/Users/cdominguez/code/gh/oclif/core/lib/main.js:49:20)
```

✅ linked plugin, same results (ESM CLI so no autocompile, but didn't got a different error).

File: src/config/ts-node.ts [hunk 1]
```diff
@@ -15,17 +15,43 @@ const debug = Debug('ts-node')
...
+    const {config} = typescript.parseConfigFileTextToJson(tsconfigPath, raw)
 
-    TS_CONFIGS[root] = tsconfig
+    if (!config || Object.keys(config.compilerOptions).length === 0) return
 
-    if (tsconfig.extends) {
+    TS_CONFIGS[root] = config
+
+    if (config.extends) {
       const {parse} = await import('tsconfck')
```
Comment (cristiand391) [inline src/config/ts-node.ts:55]: TIL about `tsconfck`

q: could we `tsconfck` to parse the whole tsconfig instead of just the `extends` block?

**Review by cristiand391 — APPROVED** [review]

**Comment by cristiand391** [comment]
**QA update**:

✅ respects `ts-node` options set in plugin tsconfig:
modified `start.ts` to get a type error, set `ts-node.transpileOnly` to `true` via tsconfig file:
```
...
config:ts-node     alwaysStrict: true,
  config:ts-node     noUnusedLocals: true,
  config:ts-node     rootDirs: [ '/Users/cdominguez/code/gh/sf/plugin-deploy-retrieve/src' ],
  config:ts-node     typeRoots: [
  config:ts-node       '/Users/cdominguez/code/gh/sf/plugin-deploy-retrieve/node_modules/@types'
  config:ts-node     ]
  config:ts-node   },
  config:ts-node   transpileOnly: true,
  config:ts-node   cwd: '/Users/cdominguez/code/gh/sf/plugin-deploy-retrieve',
...
  config:ts-node Found source file for /Users/cdominguez/code/gh/sf/plugin-deploy-retrieve/lib/hooks/deploy at /Users/cdominguez/code/gh/sf/plugin-deploy-retrieve/src/hooks/deploy +1ms
Error (1): This directory does not contain a valid Salesforce DX project.
```
Screenshot 2023-11-03 at 16 52 09

✅ comments in tsconfig, oclif can parse it. (also checked debug output, no warns/errors)
Screenshot 2023-11-03 at 16 54 01

✅ comments in base tsconfig file, still successfully parsed
Screenshot 2023-11-03 at 16 59 22

✅ no tsconfig file (also removed ref in bin/dev), commands still work:
Screenshot 2023-11-03 at 16 56 56
