### PR TITLE
feat: various fixes

### LINKED ISSUE #716: Missing `tsconfig.json:compilerOptions.rootDir` makes dev-mode load commands from `./dist/`
**Describe the bug**
If `compilerOptions.rootDir` and `compilerOptions.rootDirs` options are omitted, [tsPath](https://github.com/oclif/core/blob/main/src/config/ts-node.ts#L103-L105) defaults to `dist/` -- even in dev mode.

**To Reproduce**
1. `npx oclif generate example`
2. Remove `rootDir` from `tsconfig.json`
3. Run `./bin/dev some:command`

**Expected behavior**
`./bin/dev` should be reading commands from `./src`

**Workaround**
Add `compilerOptions.rootDir` into `tsconfig.json`

**Environment (please complete the following information):**
 - OS & version: MacOS Ventura 13.4
 - Shell/terminal & version zsh 5.9

**Additional context**
Our standard `tsconfig.json` configuration does not contain a `compilerOptions.rootDir` value. Instead, we have been relying on `compilerOptions.baseUrl` and `compilerOptions.sourceRoot` settings.

Until we realized what was going on with the `rootDir`, the developer experience was quite confusing -- we were definitely running in `dev` mode, but somehow the commands were loaded from `./dist`. There were no warning messages either, so it wasn't all that intuitive to figure out what was going wrong.

Perhaps you could add some kind of a `tsconfig.json` sanity check to make sure that the fields you require to be present are present?

### PR DESCRIPTION
**Pull request by mdonnalley**
- Support `.mts` and `.cts` file extensions (Fixes #362)
  - QA for `.cts`:
    - `git clone https://github.com/oclif/hello-world`
    - `yarn link @oclif/core`
    - rename `hello.ts` to `hello.cts`
    - `bin/dev.js hello oclif --from me`
    - `yarn tsc && bin/run.js hello oclif --from me`
  - QA for `.mts`:
    - `git clone https://github.com/oclif/hello-world-esm`
    - `yarn link @oclif/core`
    - rename `hello.ts` to `hello.mts`
    - `bin/dev.js hello oclif --from me`
    - `yarn tsc && bin/run.js hello oclif --from me`

- Support `baseUrl` for configuring source directory (Fixes #716)
  - QA:
    - `git clone https://github.com/oclif/hello-world`
    - `yarn link @oclif/core`
    - remove `rootDir` from tsconfig and replace with `baseUrl: "./src"`
    - `bin/dev.js hello oclif --from me`
- Bump ejs and other deps (Closes #821, Closes #790)
- Parallelize flag and arg caching
- Add a `Cache` class for caching the root plugin. This is better than the previous solution, which relied on the root plugin being processed by `tsPath`, which won't happen if the root plugin does not contain any commands
  - QA: passing esm-cjs interoperability tests are sufficient for QA'ing this

### CODE REVIEW

File: src/config/ts-node.ts [hunk 1]
```diff
@@ -154,9 +154,19 @@ function cannotUseTsNode(root: string, plugin: Plugin | undefined, isProduction:
 function determinePath(root: string, orig: string): string {
   const tsconfig = registerTSNode(root)
   if (!tsconfig) return orig
-  const {outDir, rootDir, rootDirs} = tsconfig.compilerOptions
-  const rootDirPath = rootDir || (rootDirs || [])[0]
-  if (!rootDirPath || !outDir) return orig
+  debug(`determining path for ${orig}`)
+  const {baseUrl, outDir, rootDir, rootDirs} = tsconfig.compilerOptions
+  const rootDirPath = rootDir || (rootDirs || [])[0] || baseUrl
```
Comment (WillieRuemmele) [inline src/config/ts-node.ts:159]: should these be `??`

**Review by WillieRuemmele — APPROVED** [review]

File: src/config/ts-node.ts (hunk 1 above)
Comment (mdonnalley) [reply src/config/ts-node.ts:159]: I'll update it

**Comment by WillieRuemmele** [comment]
### QA Notes
---
following QA docs in PR

✅ : `cts` conversion
✅ : `mts` conversion
✅ : `baseUrl` tsconfig option
✅ : caching passed by passing other QA
