### PR TITLE
fix: types on custom flags

### LINKED ISSUE #462: `Flags.integer()` isn't parsed properly when `required: true`
**Describe the bug**
When we bump v1.13.0 to v1.13.4, TypeScript starts to complain that our `Flags.integer()` with `required: true` is parsed as `number | undefined` (not `number`) and can't be assigned to `number` value. Previously, it seems the parsed `flags` had `any` type and TypeScript didn't complain. However, now it has parsed types but wrong type for `Flags.integer()` with `required: true`.

See annotations in this PR: https://github.com/autifyhq/autify-cli/pull/50/files

Note: `Flags.string()` with `required: true` is parsed properly and has `string` type.

**To Reproduce**
```typescript
  static flags = {
    "test-plan-id": Flags.integer({
      required: true,
    }),
    "create-url-replacement-request": Flags.string({
      required: true,
    }),
  };

  public async run(): Promise<void> {
    const { flags } = await this.parse(WebApiCreateUrlReplacement);
    // flags["test-plan-id"] => number | undefined
    // flags["create-url-replacement-request"] => string
```

**Expected behavior**
```typescript
  static flags = {
    "test-plan-id": Flags.integer({
      required: true,
    }),
    "create-url-replacement-request": Flags.string({
      required: true,
    }),
  };

  public async run(): Promise<void> {
    const { flags } = await this.parse(WebApiCreateUrlReplacement);
    // flags["test-plan-id"] => number
    // flags["create-url-replacement-request"] => string
```

**Screenshots**
With v1.13.4:
Screen Shot 2022-08-08 at 10 21 02 AM

With v1.13.0:
Screen Shot 2022-08-08 at 10 31 58 AM

**Environment (please complete the following information):**
 - OS & version: `Linux 559abc3f4f3f 5.15.0-43-generic #46~20.04.1-Ubuntu SMP Thu Jul 14 15:20:17 UTC 2022 x86_64 GNU/Linux`
 - Shell/terminal & version: `GNU bash, version 5.1.4(1)-release (x86_64-pc-linux-gnu)`

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by mdonnalley**
Fixes #462

### CODE REVIEW

File: src/parser/flags.ts [hunk 1]
```diff
@@ -12,15 +12,15 @@ export function build(
   defaults: Partial<OptionFlag<string>>,
 ): Definition<string>
 export function build<T>(defaults: Partial<OptionFlag<T>>): Definition<T> {
```
Comment (mshanemc) [inline src/parser/flags.ts:14]: unrelated to this PR, but back our previous conversation about GlobalFlags...I wonder if it would good to have an `O` generic property that reflects the `options` type.  

so `integer` could pass in its mix/max, dir/file could do `exists` etc

**Review by mshanemc — APPROVED** [review]
approved with one wildly speculative idea

File: src/parser/flags.ts [hunk 2]
```diff
@@ -51,14 +53,18 @@ export const integer = (opts: { min?: number; max?: number} & Partial<OptionFlag
   })()
 }
 
-export const directory = (opts: { exists?: boolean } & Partial<OptionFlag<string>> = {}): OptionFlag<string | undefined> => {
+export function directory(opts: { exists?: boolean } & Partial<OptionFlag<string>> & ({required: true} | { default: number })): OptionFlag<string>
+export function directory(opts: { exists?: boolean } & Partial<OptionFlag<string>>): OptionFlag<string | undefined>
+export function directory(opts: { exists?: boolean } & Partial<OptionFlag<string>> = {}): OptionFlag<string> | OptionFlag<string | undefined> {
```
Comment (RodEsp) [inline src/parser/flags.ts:58]: Why is the duplicated `OptionFlag<T>` return type needed here?

```suggestion
export function directory(opts: { exists?: boolean } & Partial<OptionFlag<string>> = {}): OptionFlag<string | undefined> {
```

File: src/parser/flags.ts [hunk 3]
```diff
@@ -51,14 +53,18 @@ export const integer = (opts: { min?: number; max?: number} & Partial<OptionFlag
...
   return build<string>({
     ...opts,
     parse: async (input: string) => opts.exists ? dirExists(input) : input,
   })()
 }
 
-export const file = (opts: { exists?: boolean } & Partial<OptionFlag<string>> = {}): OptionFlag<string | undefined> => {
+export function file(opts: { exists?: boolean } & Partial<OptionFlag<string>> & ({required: true} | { default: number })): OptionFlag<string>
+export function file(opts: { exists?: boolean } & Partial<OptionFlag<string>>): OptionFlag<string | undefined>
+export function file(opts: { exists?: boolean } & Partial<OptionFlag<string>> = {}): OptionFlag<string> | OptionFlag<string | undefined>  {
```
Comment (RodEsp) [inline src/parser/flags.ts:67]: Why is the duplicated `OptionFlag<T>` return type needed here?

```suggestion
export function file(opts: { exists?: boolean } & Partial<OptionFlag<string>> = {}): OptionFlag<string | undefined>  {
```

File: src/parser/flags.ts [hunk 4]
```diff
@@ -35,8 +35,10 @@ export function boolean<T = boolean>(
   } as BooleanFlag<T>
 }
 
-export const integer = (opts: { min?: number; max?: number} & Partial<OptionFlag<number>> = {}): OptionFlag<number | undefined> => {
-  return build<number>({
+export function integer(opts: Partial<OptionFlag<number>> & {min?: number; max?: number } & ({required: true} | { default: number })): OptionFlag<number>
+export function integer(opts: Partial<OptionFlag<number>> & {min?: number; max?: number }): OptionFlag<number | undefined>
+export function integer(opts: Partial<OptionFlag<number>> & {min?: number; max?: number }): OptionFlag<number> | OptionFlag<number | undefined> {
```
Comment (RodEsp) [inline src/parser/flags.ts:40]: Why is the duplicated `OptionFlag<T>` return type needed here?
```suggestion
export function integer(opts: Partial<OptionFlag<number>> & {min?: number; max?: number }): OptionFlag<number | undefined> {
```

**Review by RodEsp — CHANGES_REQUESTED** [review]

File: src/parser/flags.ts (hunk 2 above)
Comment (mdonnalley) [reply src/parser/flags.ts:58]: @RodEsp if you don't have it then the overloads don't sufficiently overlap since the function either returns an `OptionFlag<T>` or a `OptionFlag<T | undefined>`

**Review by RodEsp — APPROVED** [review]
