### PR TITLE
fix: prevent postrun hook from running on uninstalled plugins

### LINKED ISSUE #804: `postrun` hooks of uninstalled plugins are executed
**Describe the bug**

When uninstalling a plugin that has a `postrun` hook, `@oclif/core` still attempts to run the hook even though that code path no longer exists.

```
~ » sf plugins uninstall sfdx-hardis                                                                                                                                                                                                                
Uninstalling sfdx-hardis... ⢿ [2/2] Regenerating lockfile and installing missing dependencies...
Uninstalling sfdx-hardis... done
 ›   ModuleLoadError: [MODULE_NOT_FOUND] require failed to load /Users/mdonnalley/.local/share/sf/node_modules/sfdx-hardis/lib/hooks/postrun/notify: Cannot find module '/Users/mdonnalley/.local/share/sf/node_modules/sfdx-hardis/lib/hooks/postrun/notify'
 ›   Require stack:
 ›   - /Users/mdonnalley/.local/share/sf/client/2.10.2-1c35561/node_modules/@oclif/core/lib/module-loader.js
 ›   - /Users/mdonnalley/.local/share/sf/client/2.10.2-1c35561/node_modules/@oclif/core/lib/help/util.js
 ›   - /Users/mdonnalley/.local/share/sf/client/2.10.2-1c35561/node_modules/@oclif/core/lib/help/formatter.js
 ›   - /Users/mdonnalley/.local/share/sf/client/2.10.2-1c35561/node_modules/@oclif/core/lib/help/command.js
 ›   - /Users/mdonnalley/.local/share/sf/client/2.10.2-1c35561/node_modules/@oclif/core/lib/help/index.js
 ›   - /Users/mdonnalley/.local/share/sf/client/2.10.2-1c35561/node_modules/@oclif/core/lib/flags.js
 ›   - /Users/mdonnalley/.local/share/sf/client/2.10.2-1c35561/node_modules/@oclif/core/lib/cli-ux/styled/table.js
 ›   - /Users/mdonnalley/.local/share/sf/client/2.10.2-1c35561/node_modules/@oclif/core/lib/cli-ux/styled/index.js
 ›   - /Users/mdonnalley/.local/share/sf/client/2.10.2-1c35561/node_modules/@oclif/core/lib/cli-ux/index.js
 ›   - /Users/mdonnalley/.local/share/sf/client/2.10.2-1c35561/node_modules/@oclif/core/lib/command.js
 ›   - /Users/mdonnalley/.local/share/sf/client/2.10.2-1c35561/node_modules/@oclif/core/lib/index.js
 ›   - /Users/mdonnalley/.local/share/sf/client/2.10.2-1c35561/dist/cli.js
 ›   - /Users/mdonnalley/.local/share/sf/client/2.10.2-1c35561/bin/run
 ›   Code: MODULE_NOT_FOUND
```

**To Reproduce**
1. `sf plugins install sfdx-hardis`
2. `sf plugins uninstall sfdx-hardis`

**Expected behavior**
The `postrun` hook of the uninstalled plugin should not be run.

### PR DESCRIPTION
**Pull request by mdonnalley**
Fixes #804 

@W-14226831@

### CODE REVIEW

File: src/config/config.ts [hunk 1]
```diff
@@ -604,6 +604,13 @@ export class Config implements IConfig {
     await this.runHook('prerun', {Command: command, argv})
 
     const result = (await command.run(argv, this)) as T
+    // If plugins:uninstall was run, we need to remove all the uninstalled plugins
+    // from this.plugins so that the postrun hook doesn't attempt to run any
+    // hooks that might have existed in the uninstalled plugins.
+    if (c.id === 'plugins:uninstall') {
+      for (const arg of argv) this.plugins.delete(arg)
```
Comment (cristiand391) [inline src/config/config.ts:611]: `plugins uninstall` only accepts 1 arg but I'm guessing `argv` could also include `--verbose`. `this.plugins` is a map and `delete` doesn't throw if an element doesn't exist so this seems safe.

**Review by cristiand391 — APPROVED** [review]

File: src/config/config.ts (hunk 1 above)
Comment (mdonnalley) [reply src/config/config.ts:611]: Yes but I think `plugins uninstall` is supposed to take multiple arguments: https://github.com/oclif/plugin-plugins/blob/main/src/commands/plugins/uninstall.ts#L16

I'm assuming at some point `variableArgs = true` was changed to `strict = false` but the command was never updated. Iterating over the args now future proofs us from that being fixed eventually

**Comment by cristiand391** [comment]
**QA notes**:

repro'd with hardis plugin on latest sf RC.
test setup:
sf repo with this branch of core linked into it, all deduped to ensure only this branch is used and a linked plugin with a postrun hook that logs to stdout:

```
import {Hook} from '@oclif/core'

const hook: Hook<'postrun'> = async function (opts) {
  process.stdout.write(`argv: ${opts.argv}`)
}

export default hook
```

✅ `./bin/run plugins uninstall sfdx-hardis` uninstalls the plugin and doesn't try to fire postrun hook from hardis plugin, runs postrun hook from linked plugin
✅ `./bin/run plugins uninstall sfdx-hardis --verbose` same as previous test with a bunch of output from yarn, output from test hook:
```
...
Uninstalling sfdx-hardis... ⡿
success Uninstalled packages.
Uninstalling sfdx-hardis... done
argv: sfdx-hardis,--verbose%
```

✅ unlink plugin with postrun hook, no output to stdout:
```
➜  sf-cli git:(main) ./bin/run plugins uninstall @cristiand391/sf-plugin-api
Uninstalling @cristiand391/sf-plugin-api... done
```
